#!/bin/bash
#
# helmls(1) is a utility to list releases across all namespaces tiller is deployed

[[ -n $DEBUG ]] && set -x

set -eou pipefail

for ns in $(kubectl get deploy --all-namespaces -l app=helm,name=tiller -o=jsonpath="{.items[*].metadata.namespace}")
do 
  echo NAMESPACE: $ns
  helm --tiller-namespace $ns ls "$@"
done
